version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     networks:
      - default
      # - api_default
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
   web:
     depends_on:
       - db
     build:
      context: .
      args:
        INSTALL_DEPENDENCIES: vim curl htop jq
    #  entrypoint: "/var/www/html/docker-entrypoint.sh"
    #  command: ["apache2-foreground"]
     ports:
       - "8000:80"
     restart: always
     networks:
      - default
      # - api_default
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
volumes:
  db_data:
networks:
  default:
    driver: bridge
  # api_default:
  #   external: true